Added ParameterType::BINARY to UuidBinaryOrderedTimeType
ramsey/uuid-doctrine pull request #72
Opened 2019-02-28 10:09 UTC by ksowa

By adding this method, we allow Doctrine to set appropriate type for binding UUID parameters in queries. Otherwise they are bound as `ParameterType::STRING` by default.  The default approach works in MySQL, but does not in Sqlite, when e.g. running functional tests.

2019-03-04 08:51 UTC, devcube-pl commented
It should be added in `UuidBinaryType` class too

2021-11-05 16:11 UTC, Ocramius requested changes

2021-11-05 16:11 UTC, Ocramius commented on src/UuidBinaryOrderedTimeType.php
> +use Doctrine\DBAL\ParameterType;
Overall fine to have this patch, but then we need to bump the minimum supported `doctrine/dbal` to `^3`.

2022-12-20 23:39 UTC, ramsey commented
Thank you for contributing! 🎉

Apologies on the lengthy delay. I've committed this change in 41cfa5f8490f3019f1c3213c57349d801fec6812.

2022-12-20 23:39 UTC, closed without merging